[acl_build_options]
input_format="ND"
# RIFE 输入: img0/img1 各 [1,3,H,W], 须被 32 整除。
input_shape="img0:1,3,256,256;img1:1,3,256,256"

[acl_init_options]
ge.exec.precision_mode=force_fp16

[ascend_context]
plugin_custom_ops=All
